sonar.projectKey=devops-thiago_elastikjay
sonar.organization=devops-thiago

# This is the name and version displayed in the SonarCloud UI.
sonar.projectName=ElastiKJay
sonar.projectVersion=1.2.1-SNAPSHOT

# Path is relative to the sonar-project.properties file. Replace "\" by "/" on Windows.
sonar.sources=annotations/src/main,core/src/main
sonar.tests=core/src/test

# Encoding of the source code. Default is default system encoding
sonar.sourceEncoding=UTF-8

# Language
sonar.java.source=17

# Coverage reports
sonar.coverage.jacoco.xmlReportPaths=core/target/site/jacoco/jacoco.xml
sonar.junit.reportPaths=core/target/surefire-reports

# Exclude non-source files
sonar.exclusions=**/target/**

# Test exclusions
sonar.test.exclusions=**/src/test/**